### ISSUE TITLE
Install URL dead

### ISSUE THREAD

**Issue by ursus-kirk** [Taapeli/isotammi-addons#10]
It seems that the intstall URL is dead or broken. Tried it two weeks ago. Tried it today.
https://raw.githubusercontent.com/Taapeli/isotammi-addons/master/addons/gramps51 doesn't reply within gramps. It doesn't download the addon for me.
Windows 10
Gramps AIO64-5.1.5-1

**Comment by emyoulation** [comment]
I just removed one of my Isotammi add-ons (their XML exporter), added that URL to my Gramps preferences in the "Where to check" field of Third party addons management, and it found the miss exporter. It also re-installed successfully. 

(This was also on the same version of Gramps & Windows.)

Which add-on are you seeking?

**Comment by emyoulation** [comment]
Please make certain that the "Do not ask about previously notified addons" checkbox is deselected & the "What to check" is set to "New and updated addons".

**Comment by ursus-kirk** [comment]
Thank you I tried that. But still got the same error message (The add-on
library seems to be unavailable)
I'm looking to install the SuperTool

**Comment by kkujansuu** [comment]
In which language are you using Gramps? Are you using the "Plugin Manager Enhanced" add-on? There is a bug in the "Plugin Manager Enhanced" that prevents the installation of Isotammi addons if the user language is not English. The workaround is to remove that add-on while doing the installation. Or to change the language temporarily. Could this be the reason in your case?

**Comment by emyoulation** [comment]
It is a simple lookup table with a comma separated list of add-on, some descriptive info and the URL where the file is available.


It definitely isn't offline. How about if you download and install directly? They are tgz compressed. I suggest that you start with the IsotammiConfig Gramplet for the Dashboard. It lets you switch back & forth between loading add-ons from the Gramps Project & Isotammi Project add-on list with 3 clicks 
1) select the Add-on source
2) click the Save button
3) click the Gramps preferences button

![Isotammi-config.png](https://user-images.githubusercontent.com/69127217/193655341-c1ba6544-5755-4ab1-b41f-24fc97cd3529.png)

https://github.com/Taapeli/isotammi-addons/blob/master/addons/gramps51/download/IsotammiConfig.addon.tgz



https://github.com/Taapeli/isotammi-addons/tree/master/addons/gramps51/download

**Comment by emyoulation** [comment]
You've probably hit it.  He's logging in from the Netherlands.

This reminds me that we still need to revise the Gramps=Project wiki about the language sensitivity when using the Plugin Manager Enhanced.

**Comment by ursus-kirk** [comment]
So it must be a language error, nothing I did or didn't do. I did download
the source from github and installed manually

**Comment by emyoulation** [comment]
> In which language are you using Gramps? Are you using the "Plugin Manager Enhanced" add-on? There is a bug in the "Plugin Manager Enhanced" that prevents the installation of Isotammi addons if the user language is not English. The workaround is to remove that add-on while doing the installation. Or to change the language temporarily. Could this be the reason in your case?

Here's a question for Languages other than English, Finnish or Swedish (where there are corresponding addons-_**xx**_.txt file) ....
Will the Isotammi Config switchover to this server work with the Preferences Addon Manager dialog? (Even if the Plugin Manager Enhanced is installed?) If not, could the Isotammi Config throw up a warning if Gramps is not running in Finnish, Swedish or English?  The warning could insist the user switch to one of those languages before trying the Isotammi server.

references:
https://github.com/Taapeli/isotammi-addons/tree/master/addons/gramps51/listings

**Comment by emyoulation** [comment]
The Plugin Manager Enhanced has been patched to fix the fallback (to English) when an add-on list for the Language is not found.
Download the update.
