### ISSUE TITLE
Automerge can be very dangerous for sources that can only be distinguished by author

### ISSUE THREAD

**Issue by ennoborg** [Taapeli/isotammi-addons#14]
When I use the MultiMerge gramplet for sources, it has very dangerous side effects for sources that have identical titles and different authors. And I had a few of those, where the title was a generic one, just saying 'email', and I used the author field to categorize them. I had about 50 of them, and now they have all been merged into a single source, with one author, who didn't write most of them.

I was lucky in the sense that most email texts were attached to the citations, so they are still linked to their original objects, but I will still have some work on this.

Please make it so, that sources are only merged when author, title, and maybe even publication info, are the same.

**Comment by kkujansuu** [comment]
Thanks, that makes sense. Were you using the "Automerge" feature or using Multimerge in the "manual mode"?

**Comment by ennoborg** [comment]
Automerge.

Note that, on completion, it says <number> locations merged. It should say sources of course.

**Comment by kkujansuu** [comment]
> Note that, on completion, it says N locations merged. It should say sources of course.

Yes, I noticed that bug now also.

**Comment by kkujansuu** [comment]
There is now a checkbox to indicate that authors must also match when sources are automerged. It is on by default.

![image](https://user-images.githubusercontent.com/17925982/226164370-e24f5d0f-b04e-42b8-bfb9-7bd301f4387d.png)

There is a similar feature for place types.
