### ISSUE TITLE
Duplicate files in multimergegramplet directory

### ISSUE THREAD

**Issue by ennoborg** [Taapeli/isotammi-addons#15]
When I make a backup of my Linux .gramps folder to an external drive, with a Microsoft file system (exFAT or NTFS), using FreeFileSync, I see an error, because there is a conflict between files SelectPrimary.png and Selectprimary.png. These files can coexist in Linux, and probably on macOS too, but in Microsoft filesystems, they are the same, so one will always overwrite the other, and the backup of these two files results in just one file on the external drive.

Since the PNG's are nearly identical, I suggest that the file named Selectprimary.png is removed. The README.md file doesn't use that version, so it is safe to remove.

**Comment by kkujansuu** [comment]
Ok, thanks. That file was probably left there by mistake. Will be removed.
