### ISSUE TITLE
Multimerge causes Gramps to exit when spawning window over 65535 pixels

### ISSUE THREAD

**Issue by emyoulation** [Taapeli/isotammi-addons#32]
Clicking "Merge selected objects" with too many records causes a spontaneous exit of Gramps
I originally thought this was the 1,000 record limit.  But it is a GUI issue related to the window size.

This window needs a height override and vertical scrollbar if the record count is more than about 24 rows. Plus, either the buttons should be above or below the scrollable area.  Otherwise the OK and Cancel buttons are not accessible 

(Gramps.py:863206): Gdk-WARNING **: 16:13:21.430: Native Windows taller than 65535 pixels are not supported

(Gramps.py:863206): Gdk-CRITICAL **: 16:13:21.769: ../gdk/wayland/gdkdisplay-wayland.c:1426: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Segmentation fault (core dumped)

**Comment by kkujansuu** [comment]
Yes, Multimergegramplet needs a scrollbar and the buttons should be relocated.

**Comment by kkujansuu** [comment]
Scrollable window added (v1.2.4).
