### ISSUE TITLE
Missing items in SuperTool help

### ISSUE THREAD

**Issue by emyoulation** [Taapeli/isotammi-addons#33]
When comparing the Media section of the [Data Model diagram](https://gramps-project.org/wiki/index.php/Gramps_Data_Model) to the SuperTool help for Media, I did not see listings for Private, Change (which is apparently different from "Date"), or whatever undocumented datapoint Gramps uses to say whether the Path is Absolute or Relative.

**Comment by kkujansuu** [comment]
These items were intentionally left out (this applies all object types, not only Media). The idea was that SuperTool would directly expose only the most frequently used and most important attributes. This also avoids clutter in the help text and in the "SuperTool data model" diagram. Many other attributes were also omitted. Note that the SuperTool data model (https://github.com/Taapeli/isotammi-addons/blob/master/source/SuperTool/supertool.svg) does not include these attributes.

The user can always access those values simply with something like "media.private" or "obj.private" etc.

On the other hand, it might make sense to include these after all. In this case "change" should probably be represented as a DateProxy object (not just an integer). Change is the last changed date. I am not aware of an attribute that determines whether the path is absolute or relative.

**Comment by emyoulation** [comment]
Nick replied that Gramps uses the media_path_full in gramps.gen.utils.file to determine if it was an Absolute or Relative path. I did a SuperTool script to determine that. Then realized it looked up the paths repeatedly ... excessively, in fact. And rewrote it a bit.

Perhaps you could suggest improvements?

BTW, the cleanest method that I can see to share this is as a .gramps file that can be imported or pasted into the Import Text gramplet. Discourse will not accept .script filetype attachments. So if it is attached as copyable text, then I have to explain clipboarding the script, opening a text editor, pasting, saving the file with a .script extension into a specific folder, and then loading the script into SuperTool in the right category. It is somewhat fewer step for creating a SuperTool type Note or importing a .gramps file. (Although creating a single Note export is painful.)  

```
[Gramps SuperTool script file]
version=1

[title]
Media paths

[description]
Determine if Media has a Relative path or an Absolute one
See Discussion in https://gramps.discourse.group/t/how-are-relative-vs-absolute-paths-marked/5707

[category]
Media

[initial_statements]
from gramps.gen.utils.file import media_path_full, media_path
relative_path = media_path(db)

[statements]
absolute_path = media_path_full (db, path )
object_path = path
compare = "Relative path: " + relative_path
if absolute_path == object_path : compare = "Absolute path"

[filter]

[expressions]
object_path, compare

[scope]
selected

[unwind_lists]
True

[commit_changes]
False

[summary_only]
False
```

**Comment by kkujansuu** [comment]
The script looks good to me.

su 7. heinäk. 2024 klo 7.03 Emyoulation or BAMaustin (
***@***.***) kirjoitti:
