### ISSUE TITLE
[Dates] add some Transform options?

### ISSUE THREAD

**Issue by emyoulation** [Taapeli/isotammi-addons#45]
Just did some documentation on the Dates gramplet. (due to invalid date support inquires on {foreign language month names} Discourse and another {European date format} on Facebook)

Could you add some options to the Dates gramplet?

* Important... an option to [push Date text strings from selected Events back through the Gramps parser](https://gramps.discourse.group/t/making-date-input-more-flexible/2814/18). (All the existing Date Text manipulations in the Dates gramplet are still just "invalid" text string after Executing the manipulations. Users still have to go into each Date field and manually commit the updating the Date field for Gramps to re-evaluate the cleaned strings as "valid" date object. So a bulk operation in needed to make them "valid".)
* Less important... Transforms of the hyphen delimited (year, day, month) array(s) order: Reverse (a-b-c ⇒ c-b-a),  Rotation (a-b-c ⇒ c-a-b), Transposition (a-b-c ⇒ b-a-c)

**Comment by kkujansuu** [comment]
Reverse (a-b-c => c-b-a) is already taken care of the first transform in the gramplet (31.12.1888 => 1888-12-31) because the dots actually mean one of: dot, slash, hyphen or comma! Should document this...

Rotation would mean 12-31-1888 => 1888-12-31?

Transposition seems odd: 12-1888-31 = >1888-12-31? Is that really needed?

Did I understand correctly?

**Comment by emyoulation** [comment]
I did not realize that it was delimiter agnostic.  Good to know.

Rotation.  That is correct.

Transposition would only be needed if someone REALLY screwed the file. I only requested it for completeness. (Since fickle fate assures us that if it was omitted, then someone would need it.)

**Comment by emyoulation** [comment]
> What would be a good title for the first option? "Re-parse" like here?

How about Re-evaluate or Revalidate?  "Parse" is more accurate but infrequent except in computer programmer verbiage.

"Revalidate" might be best ... is almost says:  "redo valid date"

**Comment by emyoulation** [comment]
Please make the "Revalidate" the last option in the list. 

Putting it between the Find&Replace and other transforms is confusing for order of operation. Isn't the last thing you should do each cycle?

A question... can it do multiple transform at a time? Or should these be radio buttons rather than checkboxes.

**Comment by kkujansuu** [comment]
Yes. 'revalidate' should be the last thing. Maybe 'revalidate' could be automatic? It could always be executed for all selected TEXTONLY dates that the other fixes don't catch? Then there would be no need for a new checkbox.

The gramplet currently can do only one of the predefined fixes for each event/date. But multiple checkboxes can be selected - it will try each fix until one matches.

Currently the find/replace action is done *after* the other fixes (although it is presented first). It is also performed even if one of the other fixes have matched. Maybe it would make more sense to have it as the first action.

**Comment by emyoulation** [comment]
Revalidate should definitely be optional but perhaps it should be selected by default?

Where it might not be desired:
* a transform needs to be handled in a specific order prior to revalidate (e.g, ">12‐31‐1881" needs "after" transform before "rotation" transform to avoid a "1881/>12/31")

Where it might be desired as the ONLY function:
* after GEDCOM import where known formats had been marked as text strings
* after changing locale (e.g. Italian) to validate with a native language [date handler](https://gramps-project.org/wiki/index.php/Date_Handler). For imported date strings (e.g., ["before 31 december 1881" date type in Italian](https://gramps-project.org/wiki/index.php/It:Manuale_Wiki_per_Gramps_5.2_-_Inserire_e_modificare_dati:_dettaglio_-_parte_1#Finestra_di_selezione_della_data) "prima 31 dicembre 1881")

**Comment by emyoulation** [comment]
Question:

How can Find and Replace (with RegEx) be used to transform an oddly formatted span to standard format? (e.g., "12‐31-1881 - 3-14-1882" to "from 12/31/1881 to 3/14/1882" or "between 12/31/1881 and 3/14/1882") 

It seems as though a search for a space-hyphen-space could replace to the "to" or "and", the another to replace the ambiguous hyphen dates with slashes. But how can we prefix with the "from " or "between " ?

**Comment by kkujansuu** [comment]
I just pushed a new version of Dates to Github. The 'revalidate' is now automatic - I have think again, maybe it really needs to be optional.

Also changed the order of find/replace - now it is executed before the other fixes.

I did not include 'transposition'. I guess it can be done with regexes if somebody really needs it. Anyway, for completeness this is also missing: 31-1888-12 => 1888-12-31.

**Comment by kkujansuu** [comment]
The regex strings for you question above:

Find: 
    (\d+)-(\d+)-(\d+) - (\d+)-(\d+)-(\d+)

Replace: 
    from \3-\1-\2 to \6-\4-\5
    between \3-\1-\2 and \6-\4-\5

First, I could not make this work. That was because I copy-pasted the string 

    12‐31-1881 - 3-14-1882

from you message. And there the first hyphen is not a normal hyphen! It was a Unicode hyphen (hex 2010). So if you need that then the pattern should also include that character (or period to indicate any character):

    (\d+)‐(\d+)-(\d+) - (\d+)-(\d+)-(\d+)
    (\d+).(\d+)-(\d+) - (\d+)-(\d+)-(\d+)

**Comment by kkujansuu** [comment]
I don't understand why to do this in multiple steps while one regex takes care of everything. Anyway, to insert "between" at the beginning of any text use:

Find: (.*)
Replace: between \1

**Comment by emyoulation** [comment]
I do it in multiple steps because I don't  trust my RegEx skills to write a complex pattern.

Unlike SuperTool, I cannot proof the Dates gramplet functionality.

And since we're potentially mangling such a multitude of Events, I don't trust Undo. (Or that I will notice a mangling before it is unrecoverable.)

**Comment by emyoulation** [comment]
What do you think of this for a screen shot?  

I tested and (after many attempts with Errors when the values did not conform to expectations) but it should convert "31-12-1881 - 17-3-1882" to " between 31 Dec 1881 and 17 Mar 1882" (My date prefs are set to "DAY MON YEAR")  

Find:  `(\d+)-(\d+)-(\d+) - (\d+)-(\d+)-(\d+)`
Replace:  `bet \2/\1/\3 and \5/\4/\6`
![image](https://github.com/user-attachments/assets/96ea6e92-61c5-4f64-ae9d-f417b2a7c8ec)

(The wording will probably have to be tweaked again.  "Correct" can be ambiguous as it means both "fix" and "is appropriate")

**Comment by emyoulation** [comment]
The version 1.2.0 is great! Thanks for updating the 5.0, 5.1, and 5.2 archives!

Just expanded the https://www.gramps-project.org/wiki/index.php/Addon:Isotammi_addons#Dates section on the Wiki. It may be time to break SuperTool and Dates out into their own wiki pages. (I'd rater wait for Sam to resolve the problem that keeps our wiki from accepting new plug-ins. The Lau template Nick has adapted from MediWiki will make plug-in docs much more elegant. And a lot less work.)

Now I have to figure out some of the Transforms for Months as strings instead of digits. Then add documentation for that and changing the locale. (I think that maybe using the Dates addon with the PortableApps Gramps for Windows might be the key there. It comes with all the languages installed. That makes one less complication to document.)

Posted a suggestion for the Facebook person to upgrade to 1.2.0 of Dates. And helped another find Filter+.

**Comment by emyoulation** [comment]
Additional transforms added. Can do the revalidate with the find&replace (find self, replace with self). Since every transform revalidates and there is no separate Revalidate.
