### ISSUE TITLE
README.md needs revision to warn that styles and links are lost during merges.

### ISSUE THREAD

**Issue by emyoulation** [Taapeli/isotammi-addons#6]
The [Special handling for notes](https://github.com/Taapeli/isotammi-addons/blob/master/source/multimergegramplet/README.md#special-handling-for-notes) should advise that text stylings (italic, bold, underline, font face and size, foreground and background colors) and Links are removed during a "Combine text from all notes" merge. Styling is only preserved when selecting the "Use text from primary note only" option.

The Note markup format is extremely fragile. (The note's "text" chunk is followed by a series of named "style" chunks with a range of "start" and "end" character positions.) It does not use hidden tags embedded inline. 

```
  <notes>
    <note handle="_e96786299766d15816aca4bb6fc" change="1651796678" id="N000000" type="Person Note">
      <text>John Smith was here
note
source
Event
place
family
citation
</text>
      <style name="underline">
        <range start="25" end="31"/>
      </style>
      <style name="fontcolor" value="#cc0000">
        <range start="44" end="50"/>
      </style>
      <style name="link" value="gramps://Person/handle/e96785701031a9037687461f347">
        <range start="0" end="10"/>
      </style>
    </note>
  </notes>
```

all the `style` chunks are dropped during the merge.

**Comment by kkujansuu** [comment]
Fixed so that styles and links are preserved after merging.
