### ISSUE TITLE
Can multimerge be made to work on events?

### ISSUE THREAD

**Issue by bnapolitano** [Taapeli/isotammi-addons#8]
I have a lot of shared events (especially census) that I would like to merge, but 2 at a time is very time consuming.  Can multimerge be made to work on events?

Multimerge has been really helpful with multiple duplicate notes, thanks for this tool!

**Comment by kkujansuu** [comment]
Yes. There is now a new version (1.1.2) that supports events (and also citations and media). Thanks for the suggestion.

**Comment by bnapolitano** [comment]
The additions work great.  Thank you for the quick turnaround!
